### ISSUE TITLE
Make fails with kernel 5.17+

### ISSUE THREAD

**Issue by bazeon** [fastoe/RTL8812BU#28]
Running make on kernel 5.17 results in the following

fredrik@pop-os:~/RTL8812BU-5.8.7$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.17.5-76051705-generic/build M=/home/fredrik/RTL8812BU-5.8.7  modules
make[1]: Entering directory '/usr/src/linux-headers-5.17.5-76051705-generic'
  CC [M]  /home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.o
/home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.c: In function ‘thread_exit’:
/home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.c:1302:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1302 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
/home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.c: In function ‘rtw_change_ifname’:
/home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.c:2564:28: warning: passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2564 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.c:922:24: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  922 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /home/fredrik/RTL8812BU-5.8.7/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1837: /home/fredrik/RTL8812BU-5.8.7] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.17.5-76051705-generic'
make: *** [Makefile:2390: modules] Error 2

**Comment by vnylbscr** [comment]
same error on my machine. did you find any solution?

**Comment by spazm-ma** [comment]
You need the 5.8.7 branch/tag:

https://github.com/fastoe/RTL8812BU#for-kernel-511-or-later-please-clone-the-v587-branch

try that and see if it helps.

**Comment by koko004** [comment]
> You need the 5.8.7 branch/tag:
> 
> https://github.com/fastoe/RTL8812BU#for-kernel-511-or-later-please-clone-the-v587-branch
> 
> try that and see if it helps.

Not works on 5.18
![16572227532337272901893223228233](https://user-images.githubusercontent.com/10567364/177858485-2bb5bacf-93ca-4094-9de9-b58a72b4a52a.jpg)

**Comment by almeidagabriela** [comment]
The error persists even with the 5.8.7 branch

<pre><font color="#CC0000"><b>error: </b></font>implicit declaration of function ‘<b>complete_and_exit</b>’ [<font color="#CC0000"><b>-Werror=implicit-function-declaration</b></font>]
 1302 |         <font color="#CC0000"><b>complete_and_exit</b></font>(comp, 0);
      |         <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~</b></font>
<b>/home/galmeida/RTL8812BU/os_dep/osdep_service.c:</b> In function ‘<b>rtw_change_ifname</b>’:
<b>/home/galmeida/RTL8812BU/os_dep/osdep_service.c:2564:28:</b> <font color="#75507B"><b>warning: </b></font>passing argument 1 of ‘<b>_rtw_memcpy</b>’ discards ‘<b>const</b>’ qualifier from pointer target type [<font color="#75507B"><b>-Wdiscarded-qualifiers</b></font>]
 2564 |         _rtw_memcpy(<font color="#75507B"><b>pnetdev-&gt;dev_addr</b></font>, adapter_mac_addr(padapter), ETH_ALEN);
      |                     <font color="#75507B"><b>~~~~~~~^~~~~~~~~~</b></font>
<b>/home/galmeida/RTL8812BU/os_dep/osdep_service.c:922:24:</b> <font color="#06989A"><b>note: </b></font>expected ‘<b>void *</b>’ but argument is of type ‘<b>const unsigned char *</b>’
  922 | void _rtw_memcpy(<font color="#06989A"><b>void *dst</b></font>, const void *src, u32 sz)
      |                  <font color="#06989A"><b>~~~~~~^~~</b></font>
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /home/galmeida/RTL8812BU/os_dep/osdep_service.o] Erro 1
make[1]: *** [Makefile:1837: /home/galmeida/RTL8812BU] Erro 2
make[1]: Saindo do diretório &apos;/usr/src/linux-headers-5.17.15-76051715-generic&apos;
make: *** [Makefile:2390: modules] Erro 2</pre>

**Comment by BeadyRaindrop** [comment]
Did anyone find a solution to this? Having the same err on kernel 5.18

**Comment by BeadyRaindrop** [comment]
Think I have found a working driver repo
https://github.com/morrownr/88x2bu-20210702
Still using kernel 5.18 (Kali), using the TPLink Archer T3U USB Wifi Adapter

**Comment by mosoriob** [comment]
It didn't work for me. `5.17.5-76051705-generic`
This driver https://github.com/morrownr/88x2bu-20210702 works.
