### ISSUE TITLE
Error while running the make command on Arch Linux Kernel version 5.18.10

### ISSUE THREAD

**Issue by EG017** [fastoe/RTL8812BU#32]
when i try to run the make command i get this back 

Xavier% make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.10-arch1-1/build M=/home/xavier/RTL8812BU  modules
make[1]: Entering directory '/usr/lib/modules/5.18.10-arch1-1/build'
  CC [M]  /home/xavier/RTL8812BU/os_dep/osdep_service.o
/home/xavier/RTL8812BU/os_dep/osdep_service.c: In function ‘thread_exit’:
/home/xavier/RTL8812BU/os_dep/osdep_service.c:1302:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1302 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
/home/xavier/RTL8812BU/os_dep/osdep_service.c: In function ‘isFileReadable’:
/home/xavier/RTL8812BU/os_dep/osdep_service.c:2224:9: error: unknown type name ‘mm_segment_t’
 2224 |         mm_segment_t oldfs;
      |         ^~~~~~~~~~~~
/home/xavier/RTL8812BU/os_dep/osdep_service.c: In function ‘retriveFromFile’:
/home/xavier/RTL8812BU/os_dep/osdep_service.c:2269:9: error: unknown type name ‘mm_segment_t’
 2269 |         mm_segment_t oldfs;
      |         ^~~~~~~~~~~~
/home/xavier/RTL8812BU/os_dep/osdep_service.c: In function ‘storeToFile’:
/home/xavier/RTL8812BU/os_dep/osdep_service.c:2312:9: error: unknown type name ‘mm_segment_t’
 2312 |         mm_segment_t oldfs;
      |         ^~~~~~~~~~~~
/home/xavier/RTL8812BU/os_dep/osdep_service.c: In function ‘rtw_change_ifname’:
/home/xavier/RTL8812BU/os_dep/osdep_service.c:2564:28: warning: passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2564 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/home/xavier/RTL8812BU/os_dep/osdep_service.c:922:24: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  922 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /home/xavier/RTL8812BU/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1838: /home/xavier/RTL8812BU] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.18.10-arch1-1/build'
make: *** [Makefile:2390: modules] Error 2

ive tried to fix this by installing the correct linux headers but that did not fix it and i did clone the v5.8.7 branch
Thanks for taking a look at this.

**Comment by denissabramovs** [comment]
I think that i have the same error:
```
  CC [M]  /tmp/RTL8812BU/core/rtw_btcoex_wifionly.o
  CC [M]  /tmp/RTL8812BU/core/rtw_btcoex.o
  CC [M]  /tmp/RTL8812BU/core/rtw_beamforming.o
  CC [M]  /tmp/RTL8812BU/core/rtw_odm.o
  CC [M]  /tmp/RTL8812BU/core/rtw_rm.o
  CC [M]  /tmp/RTL8812BU/core/rtw_rm_fsm.o
  CC [M]  /tmp/RTL8812BU/core/rtw_rm_util.o
  CC [M]  /tmp/RTL8812BU/core/efuse/rtw_efuse.o
  CC [M]  /tmp/RTL8812BU/os_dep/osdep_service.o
/tmp/RTL8812BU/os_dep/osdep_service.c: In function ‘thread_exit’:
/tmp/RTL8812BU/os_dep/osdep_service.c:1302:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1302 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
/tmp/RTL8812BU/os_dep/osdep_service.c: In function ‘rtw_change_ifname’:
/tmp/RTL8812BU/os_dep/osdep_service.c:2564:28: warning: passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2564 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/tmp/RTL8812BU/os_dep/osdep_service.c:922:24: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  922 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /tmp/RTL8812BU/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1831: /tmp/RTL8812BU] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.17.0-051700-generic/build'
make: *** [Makefile:2390: modules] Error 2
```

**Comment by FuexFollets** [comment]
I have the same error but i am using `5.18.14-arch1-1`

**Comment by mosoriob** [comment]
https://github.com/morrownr/88x2bu-20210702 works on `5.17.5-76051705-generic `
