### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by speckly** [fastoe/RTL8812BU#52]
OS: Arch Linux x86_64 
Kernel: 6.8.9-arch1-2
Shell: bash 5.2.26

i cloned the v5.13.1 branch
this is the error when running `make`
```
[speckles@speckly RTL8812BU]$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.8.9-arch1-2/build M=/home/speckles/Downloads/RTL8812BU  modules
make[1]: Entering directory '/usr/lib/modules/6.8.9-arch1-2/build'
  CC [M]  /home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.o
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:1087:6: warning: no previous prototype for ‘rtw_regsty_load_target_tx_power’ [-Wmissing-prototypes]
 1087 | void rtw_regsty_load_target_tx_power(struct registry_priv *regsty)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:1703:14: warning: no previous prototype for ‘rtw_classify8021d’ [-Wmissing-prototypes]
 1703 | unsigned int rtw_classify8021d(struct sk_buff *skb)
      |              ^~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:1839:5: warning: no previous prototype for ‘rtw_ndev_init’ [-Wmissing-prototypes]
 1839 | int rtw_ndev_init(struct net_device *dev)
      |     ^~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:1852:6: warning: no previous prototype for ‘rtw_ndev_uninit’ [-Wmissing-prototypes]
 1852 | void rtw_ndev_uninit(struct net_device *dev)
      |      ^~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:1912:6: warning: no previous prototype for ‘rtw_hook_if_ops’ [-Wmissing-prototypes]
 1912 | void rtw_hook_if_ops(struct net_device *ndev)
      |      ^~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:1994:5: warning: no previous prototype for ‘rtw_os_ndev_alloc’ [-Wmissing-prototypes]
 1994 | int rtw_os_ndev_alloc(_adapter *adapter)
      |     ^~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c: In function ‘rtw_ethtool_get_drvinfo’:
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:2050:17: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Wimplicit-function-declaration]
 2050 |                 strlcpy(info->driver, wiphy_dev(wdev->wiphy)->driver->name,
      |                 ^~~~~~~
      |                 strscpy
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c: At top level:
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:2149:5: warning: no previous prototype for ‘rtw_os_ndev_register’ [-Wmissing-prototypes]
 2149 | int rtw_os_ndev_register(_adapter *adapter, const char *name)
      |     ^~~~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:2300:5: warning: no previous prototype for ‘rtw_os_ndevs_alloc’ [-Wmissing-prototypes]
 2300 | int rtw_os_ndevs_alloc(struct dvobj_priv *dvobj)
      |     ^~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:2352:6: warning: no previous prototype for ‘rtw_os_ndevs_free’ [-Wmissing-prototypes]
 2352 | void rtw_os_ndevs_free(struct dvobj_priv *dvobj)
      |      ^~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:2484:4: warning: no previous prototype for ‘rtw_init_default_value’ [-Wmissing-prototypes]
 2484 | u8 rtw_init_default_value(_adapter *padapter)
      |    ^~~~~~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:3721:5: warning: no previous prototype for ‘rtw_os_ndevs_register’ [-Wmissing-prototypes]
 3721 | int rtw_os_ndevs_register(struct dvobj_priv *dvobj)
      |     ^~~~~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:3838:6: warning: no previous prototype for ‘netdev_br_init’ [-Wmissing-prototypes]
 3838 | void netdev_br_init(struct net_device *netdev)
      |      ^~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:4155:6: warning: no previous prototype for ‘ips_netdrv_open’ [-Wmissing-prototypes]
 4155 | int  ips_netdrv_open(_adapter *padapter)
      |      ^~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:4348:5: warning: no previous prototype for ‘pm_netdev_open’ [-Wmissing-prototypes]
 4348 | int pm_netdev_open(struct net_device *pnetdev, u8 bnormal)
      |     ^~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:4476:5: warning: no previous prototype for ‘pm_netdev_close’ [-Wmissing-prototypes]
 4476 | int pm_netdev_close(struct net_device *pnetdev, u8 bnormal)
      |     ^~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:5174:5: warning: no previous prototype for ‘rtw_suspend_normal’ [-Wmissing-prototypes]
 5174 | int rtw_suspend_normal(_adapter *padapter)
      |     ^~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:5587:6: warning: no previous prototype for ‘rtw_mi_resume_process_normal’ [-Wmissing-prototypes]
 5587 | void rtw_mi_resume_process_normal(_adapter *padapter)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.c:5620:5: warning: no previous prototype for ‘rtw_resume_process_normal’ [-Wmissing-prototypes]
 5620 | int rtw_resume_process_normal(_adapter *padapter)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /home/speckles/Downloads/RTL8812BU/os_dep/linux/os_intfs.o] Error 1
make[2]: *** [/usr/lib/modules/6.8.9-arch1-2/build/Makefile:1921: /home/speckles/Downloads/RTL8812BU] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.8.9-arch1-2/build'
make: *** [Makefile:2506: modules] Error 2
[speckles@speckly RTL8812BU]$
```

**Comment by Wang-Yan-Hao** [comment]
OS: Ubuntu 24.04.1 LTS
Kernel: 6.8.0-45-generic
Shell: bash 5.2.21(1)-release (x86_64-pc-linux-gnu)

I’m experiencing the same issue, but I attempted to replace the original `strlcpy` function with `strscpy` ([related patch](https://lore.kernel.org/lkml/202401191141.F6902E74D@keescook/t/)) and then recompiled the module. However, I encountered the following errors:

```
/home/kola/git_projects/RTL8812BU/os_dep/linux/usb_intf.c:363:17: error: ‘struct usb_driver’ has no member named ‘drvwrap’
  363 |         .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
      |                 ^~~~~~~
/home/kola/git_projects/RTL8812BU/os_dep/linux/usb_intf.c:363:43: error: initialization of ‘const char *’ from incompatible pointer type ‘void (*)(struct device *)’ [-Werror=incompatible-pointer-types]
  363 |         .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
```

It seems that the `struct usb_driver` in the Linux kernel has changed ([related issue](https://github.com/aircrack-ng/rtl8812au/issues/1142)). Therefore, I believe making this work with kernel versions 6.8 and above will require some effort.

**Comment by Wang-Yan-Hao** [comment]
I see another [repo](https://github.com/morrownr/88x2bu-20210702?tab=readme-ov-file) which may help.
